# This is the config file for greposync that defines default values
# Visit the documentation at https://ccremer.github.io/greposync

.github/workflows/test.yml:
  codeclimate:
    reporterID: 38a41dde51e26878e774848c2654bba1082ad39703571505e877575b2a9695e3
