name: Build

on:
  push:
    branches:
    - "*"
    tags-ignore:
    - "*"
  pull_request:
    types: [opened, reopened]

env:
  GO_VERSION: "^1.14.3"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: go-mod-build
    - uses: goreleaser/goreleaser-action@v1
      with:
        args: release --snapshot --skip-sign

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: go-mod-build
    - name: Test & Publish Code Coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: 38a41dde51e26878e774848c2654bba1082ad39703571505e877575b2a9695e3
      with:
        coverageCommand: make test
        prefix: ${{ github.event.repository.name }}
        coverageLocations:
          "${{github.workspace}}/c.out:gocov"
